# Generated by Django 6.0.4 on 2026-06-30 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_medecin_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe_sanguin', models.CharField(blank=True, max_length=10, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('antecedents', models.TextField(blank=True, null=True)),
                ('maladies_chroniques', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossiermedical', to='medical.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('motif', models.TextField()),
                ('diagnostic', models.TextField(blank=True, null=True)),
                ('traitement', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='medical.medecin')),
                ('dossier_medical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='medical.dossiermedical')),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_examen', models.CharField(choices=[('analyse', 'Analyse'), ('radio', 'Radio'), ('echo', 'Échographie'), ('irm', 'IRM'), ('autre', 'Autre')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('resultat', models.TextField(blank=True, null=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='examens/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('dossier_medical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens', to='medical.dossiermedical')),
            ],
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicaments', models.TextField()),
                ('duree', models.CharField(blank=True, max_length=100, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnance', to='medical.consultation')),
            ],
        ),
    ]
