# Generated by Django 6.0.4 on 2026-07-05 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0004_dossiermedical_consultation_examen_ordonnance'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='is_verrouille',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultation',
            name='rdv',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='medical.rendezvous'),
        ),
        migrations.AddField(
            model_name='examen',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examens', to='medical.consultation'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='en_attente', max_length=20),
        ),
    ]
