# Generated by Django 6.0.4 on 2026-07-07 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0006_centresante_latitude_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='commentaire_medecin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='nouveau_jour',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='nouvelle_heure',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('reporte', 'Reporté'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='en_attente', max_length=20),
        ),
    ]
