# Generated by Django 6.0.4 on 2026-07-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0007_rendezvous_commentaire_medecin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='date_cloture',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='statut_consultation',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('terminee', 'Terminée')], default='en_cours', max_length=20),
        ),
    ]
