# Generated by Django 6.0.4 on 2026-07-19 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0008_consultation_cloture'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rendezvous',
            constraint=models.UniqueConstraint(condition=models.Q(('statut__in', ['en_attente', 'confirme'])), fields=('medecin', 'jour', 'heure'), name='unique_active_rdv_per_slot'),
        ),
    ]
